[project]
name = "gd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9,<3.10"
dependencies = [
    "joblib>=1.4.2",
    "pandas>=2.2.3",
    "scikit-learn==1.5.2",
]
